spring:
  application:
    name: syma-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.144.198.141:3306/syma?useUnicode=true&autoReconnect=true
    username: root
    password: 123456



wx:
  appid: wx429f479a7ab7620e
  secret: 6b61af287e1a7a06c503c2032bbdc830
  code2Session: https://api.weixin.qq.com/sns/jscode2session?appid=%s&secret=%s&js_code=%s&grant_type=authorization_code

